services:
  - type: web
    name: telegram-videobot
    env: python
    plan: free
    buildCommand: bash render_build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: WEBAPP_URL
        fromSecret: WEBAPP_URL
      - key: SIGNALING_SECRET
        fromSecret: SIGNALING_SECRET